### ISSUE TITLE
Errors during login swallowed by generic LoginException

### ISSUE THREAD

**Issue by neerajkumarjha** [forcedotcom/SalesforcePy#34]
Traceback (most recent call last):
  File "login.py", line 17, in <module>
    login_results = client.login();
  File "/salesForce/python/SalesforcePy/SalesforcePy/commons.py", line 103, in decorated
    return func(self, *args, **function_kwarg)
  File "/salesForce/python/SalesforcePy/SalesforcePy/sfdc.py", line 149, in login
    raise LoginException("Failed to perform `login` request")
SalesforcePy.sfdc.LoginException: Failed to perform `login` request

SalesforcePy.sfdc.LoginException: Failed to perform `login` request

Not able to understand.

**Comment by caffalaughrey** [comment]
While this exception is being thrown by design ("don't allow use of the client if I can't login"), I don't think the design makes sense anymore.  `login_response` (an `sfdc.Login` object) contains a list called `exceptions` to which any errors raised during the request should be appended (as is the case for all classes that inherit `commons.BaseRequest`.)  For this reason I think it makes the most sense not to raise an exception [here](https://github.com/forcedotcom/SalesforcePy/blob/385aeedfb57d20c3bbd09c280e1223620a7da92e/SalesforcePy/sfdc.py#L148) (ie. lines 148-149 here can be reverted.)

Having said that, I believe a check against None is still necessary to determine whether to set the client state:
```python
    if req is not None:
        self.session_id = login_response.get_session_id()
        self.set_instance_url(req.get('instance_url', str()))
        self.set_api_version()
```
...and for that reason, docs also need updating to advise developers to check the `exceptions` list is empty before continuing to use the client.  In fact, the documentation likely needs a section on the use of `exceptions` overall.
